name: LobbyCore
version: '${version}'
main: me.qubique.lobbycore.LobbyCore
commands:
  hologram:
    description: hologram
    usage: /<commands>
  armorstand:
    description: armorstand
    usage: /<commands>
